module.exports = async function (self) {
	self.setVariableDefinitions([
		{ name: 'FocusPosition', variableId: 'FPos' },
		{ name: 'IrisPosition', variableId: 'IPos' },
		{ name: 'ZoomPosition', variableId: 'ZPos' },
		{ name: 'FocusIncrement', variableId: 'FStep' },
		{ name: 'IrisIncrement', variableId: 'IStep' },
		{ name: 'ZoomIncrement', variableId: 'ZStep' },
		{ name: 'PanJogSpeed', variableId: 'PanSpeed' },
		{ name: 'TiltJogSpeed', variableId: 'TiltSpeed' },
		{ name: 'M3JogSpeed', variableId: 'M3Speed' },
		{ name: 'M4JogSpeed', variableId: 'M4Speed' },
		{ name: 'TN1Speed', variableId: 'TN1Speed' },
		{ name: 'TN2Speed', variableId: 'TN2Speed' },
		{ name: 'TN3Speed', variableId: 'TN3Speed' },
		{ name: 'RollSpeed', variableId: 'RollSpeed' },
		{ name: 'FocusSpeed', variableId: 'FocusSpeed' },
		{ name: 'Preset0Status', variableId: 'Pst0Stat'},
		{ name: 'Preset1Status', variableId: 'Pst1Stat'},
		{ name: 'Preset2Status', variableId: 'Pst2Stat'},
		{ name: 'Preset3Status', variableId: 'Pst3Stat'},
		{ name: 'Preset4Status', variableId: 'Pst4Stat'},
		{ name: 'Preset5Status', variableId: 'Pst5Stat'},
		{ name: 'Preset6Status', variableId: 'Pst6Stat'},
		{ name: 'Preset7Status', variableId: 'Pst7Stat'},
		{ name: 'Preset8Status', variableId: 'Pst8Stat'},
		{ name: 'Preset9Status', variableId: 'Pst9Stat'},
		{ name: 'Preset10Status', variableId: 'Pst10Stat'},
		{ name: 'Preset11Status', variableId: 'Pst11Stat'},
		{ name: 'Preset12Status', variableId: 'Pst12Stat'},
		{ name: 'Preset13Status', variableId: 'Pst13Stat'},
		{ name: 'Preset14Status', variableId: 'Pst14Stat'},
		{ name: 'Preset15Status', variableId: 'Pst15Stat'},
		{ name: 'Preset16Status', variableId: 'Pst16Stat'},
		{ name: 'Preset17Status', variableId: 'Pst17Stat'},
		{ name: 'Preset18Status', variableId: 'Pst18Stat'},
		{ name: 'Preset19Status', variableId: 'Pst19Stat'},
		{ name: 'Preset20Status', variableId: 'Pst20Stat'},
		{ name: 'Preset21Status', variableId: 'Pst21Stat'},
		{ name: 'Preset22Status', variableId: 'Pst22Stat'},
		{ name: 'Preset23Status', variableId: 'Pst23Stat'},
		{ name: 'Preset24Status', variableId: 'Pst24Stat'},
		{ name: 'Preset25Status', variableId: 'Pst25Stat'},
		{ name: 'Preset26Status', variableId: 'Pst26Stat'},
		{ name: 'Preset27Status', variableId: 'Pst27Stat'},
		{ name: 'Preset28Status', variableId: 'Pst28Stat'},
		{ name: 'Preset29Status', variableId: 'Pst29Stat'},
		{ name: 'Preset30Status', variableId: 'Pst30Stat'},
		{ name: 'Last TCP Response', variableId: 'tcp_response' }
	])
}
